config/routes.rb
WaKeyPress::Application.routes.draw do
  

  resources :games do
    resources :players
  end
  
  match 'facilitator' => 'wa#facilitator'
  
  match 'clear' => 'wa#clear'
  
  match 'zoom/new' => "s3media#create"
  
  match 'zoom/images' => 'zoomcollection#getImages'
  

  root :to => 'wa#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
end

app/models/zoom_collection.rb
class ZoomCollection < ActiveRecord::Base
end

app/models/zoom_photo.rb
class ZoomPhoto < ActiveRecord::Base
end

app/controllers/S3media_controller.rb
class S3mediaController < ApplicationController
  # create the document in rails, then send json back to our javascript to populate the form that will be
  # going to amazon.
  def create
      if ZoomCollection.exists?(:name => params[:collection][:title])
        @document = ZoomCollection.find_by_name(params[:collection][:title])
      else
        @document = ZoomCollection.create(:name => params[:collection][:title])
        @document.save
      end
      @image = ZoomPhoto.create(:collection_id => @document.id);
      s3_key = Date.today.year.to_s + "/" + Date.today.month.to_s + "/" + Date.today.day.to_s + "/" + @image.id.to_s + "." + params[:image][:title].split(".").last
      full_url = "https://s3.amazonaws.com/" + S3["bucket"] + "/" + s3_key
      @image.s3_key = s3_key
      @image.full_url = full_url
      @image.save
      render :json => {
        :success => true,
        :message => "S3 write request approved.",
        :url => @image.full_url,
        :s3 => {
          :policy => s3_upload_policy_document, 
          :signature => s3_upload_signature, 
          :key => @image.s3_key, 
          :success_action_redirect => "/"
        }
      }.to_json
  end
  
  # just in case you need to do anything after the document gets uploaded to amazon.
  # but since we are sending our docs via a hidden iframe, we don't need to show the user a 
  # thank-you page.
  def s3_confirm
    head :ok
  end
 
  private
  
  # generate the policy document that amazon is expecting.
  def s3_upload_policy_document
    return @policy if @policy
    ret = {"expiration" => 5.minutes.from_now.utc.xmlschema,
      "conditions" =>  [ 
        {"bucket" =>  S3["bucket"]}, 
        ["starts-with", "$key", @image.s3_key], 
        {"acl" => "public-read"},
        {"success_action_status" => "200"},
        ["content-length-range", 0, 1048576]
      ]
    }
    @policy = Base64.encode64(ret.to_json).gsub(/\n/,'')
  end

  # sign our request by Base64 encoding the policy document.
  def s3_upload_signature
    signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'), S3["secret_access_key"], s3_upload_policy_document)).gsub("\n","")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, :notice => 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @game = Game.find(params[:game_id])
    @player = @game.players.create(params[:player])

    redirect_to game_path(@game)
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, :notice => 'Player was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :ok }
    end
  end
end

app/controllers/wa_controller.rb
class WaController < ApplicationController 
  def index
  end
  
  def facilitator
    @collections = ZoomCollection.find :all
  end
  
  def clear
     @game = Game.find(1)
     @game.status = "stopped"
     @game.start_time =  Time.now
     @game.duration = 0
     @game.team_1_score = 0
     @game.team_2_score = 0
     @game.return_location = ""
     @game.players.each do |player|
          player.destroy
     end
     @game.save
     redirect_to game_path(@game)
  end
end

app/controllers/zoomcollection_controller.rb
class ZoomcollectionController < ApplicationController
  def getImages
     collection = ZoomCollection.find_by_name(params[:name])
     images = ZoomPhoto.find_all_by_collection_id(collection.id)
     render :json => {
        :success => true,
        :message => "Returned images",
        :images => images
      }.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :team_1_score %><br />
    <%= f.number_field :team_1_score %>
  </div>
  <div class="field">
    <%= f.label :team_2_score %><br />
    <%= f.number_field :team_2_score %>
  </div>
  <div class="field">
    <%= f.label :return_location %><br />
    <%= f.text_field :return_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Start time</th>
    <th>Duration</th>
    <th>Team 1 score</th>
    <th>Team 2 score</th>
    <th>Return location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.status %></td>
    <td><%= game.start_time %></td>
    <td><%= game.duration %></td>
    <td><%= game.team_1_score %></td>
    <td><%= game.team_2_score %></td>
    <td><%= game.return_location %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @game.status %>
</p>

<p>
  <b>Start time:</b>
  <%= @game.start_time %>
</p>

<p>
  <b>Duration:</b>
  <%= @game.duration %>
</p>

<p>
  <b>Team 1 score:</b>
  <%= @game.team_1_score %>
</p>

<p>
  <b>Team 2 score:</b>
  <%= @game.team_2_score %>
</p>

<p>
  <b>Return location:</b>
  <%= @game.return_location %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

<h2>Players:</h2>
<% @game.players.each do |player| %>
  <p>
    <b>Name:</b>
    <%= player.player_id %>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaKeyPress</title>
  <%= stylesheet_link_tag "bootstrap.min" %>
  <%= stylesheet_link_tag "jquery.fileupload-ui" %>
  <%= stylesheet_link_tag "application" %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/jquery-ui.min.js"></script>
  <%= javascript_include_tag "date" %>
  <%= javascript_include_tag "jquery.ui.widget" %>
  <%= javascript_include_tag "jquery.iframe-transport" %>
  <%= javascript_include_tag "jquery.fileupload" %>
  <%= javascript_include_tag "carousel" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container wa-client alert-success round">
        <h1 id="yourteam"></h1>
    	<div id="WACanvas"style="height: auto; width: 100%;"> 
    	    <noscript>
    	        Javascript is required to experience web.alive. Please enable javascript support in your browser and refresh
    	    </noscript>
    	</div>
    	 <%= yield %>	
    </div>

	<script type="text/javascript" src="http://wa3530.avayalive.com/3530/html/javascript/WAInit.js"></script> 
    <script language="JavaScript">	
        $('#WACanvas').height($('#WACanvas').width() /2);
        //$('.team').height($('#WACanvas').width() /2 + 60);
        $('#WACanvas').width($('#WACanvas').width());  
        WAUrlVars = {
    	    "XResolution":  $('#WACanvas').width() ,
    		"YResolution": $('#WACanvas').height(),
    	    "Language":"en","GenericParam": "?ReqAnonConn=false", "URLOverwriteAllowed": "true"
    	}
    	WAStart();
    	$('iframe').height($('#WACanvas').width() /2);
        $('iframe').width($('#WACanvas').width());
        $("#WACanvas").css("background-color", "#DFF0D8");
        $("#WACanvas").css("background-image", "");
    </script>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= f.number_field :team %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.player_id %></td>
    <td><%= player.team %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @player.player_id %>
</p>

<p>
  <b>Team:</b>
  <%= @player.team %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/wa/facilitator.html.erb
<%= javascript_include_tag "kpa-facilitator" %>

<div class="alert-error team1 pregame team">
    <h2>Team 1</h2>
    <ul id="team1list">
    </ul>
</div>
<div class="pregame controls">
    <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
          <li id="kpa-controls-btn"  class="active"><a href="#" data-toggle="tab">Key Punch</a></li>
          <li id="zoom-controls-btn" class=""><a href="#" data-toggle="tab">Zoom</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="kpa-controls">
              <div class="form-horizontal row">
                  <div class="span4">
                      <div class="control-group">
                            <label class="control-label" for="return-location">Teleport Location:</label>
                            <select id="return-location">
                                <option>CampFire</option>
                            </select>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="duration">Duration (min):</label>
                            <select id="duration">
                                <option>15</option>
                                <option>30</option>
                                <option>45</option>
                            </select>
                        </div>
                    </div>
                    <div class="span2">
                        <div class="btn btn-success" id="startbtn">
                            Start Game 
                        </div>
                        <div class="btn btn-danger" id="clearbtn">
                            Clear Game
                        </div>
                    </div>
                </div>
          </div>
          <div class="tab-pane" id="zoom-controls">
                <div class="row">
                    <div class="span4 right-border">
                        <h4>Use a new or existing photo collection?</h4>
                        <div class="control-group">
                            <div class="controls">
                                <label class="radio inline">
                                    <input type="radio" name="optionsRadios" id="existing-collection" value="option1" checked=""/>
                                    Existing
                                </label>
                                <label class="radio inline">
                                    <input type="radio" name="optionsRadios" id="new-collection" value="option2" />
                                    New
                                </label>
                            </div>
                        </div>
                        <div class="form-horizontal">
                            <div class="control-group" id="existing-container">
                                <label class="control-label" for="photo-collections">Collection:</label>
                                <select class="inline" id="photo-collections">
                                    <option>
                                        
                                    </option>
                                    <%@collections.each do |collection|%>
                                        <option>
                                            <%=collection.name%>
                                        </option>
                                    <%end%>
                                </select>
                            </div>
                            <div id="new-container" class="hidden">
                                <div class="control-group" >
                                    <label class="control-label" for="collection-title">
                                        Title: 
                                    </label>
                                    <input type="text" id="collection-title"/>  
                                </div>
                                <form action='https://tipontia.s3.amazonaws.com' enctype='multipart/form-data' id='file_upload' method='post'>
                                    <input name='key' type='hidden' />
                                    <input name='AWSAccessKeyId' type='hidden' value='AKIAJFIREA26AFJBIXWQ' />
                                    <input name='acl' type='hidden' value='public-read' />
                                    <input name='success_action_status' type='hidden' value='200' />
                                    <input name='policy' type='hidden' />
                                    <input name='signature' type='hidden' />
                                    <div class="file-upload">
                                      <span class="btn btn-info fileinput-button">
                                          <span><i class="icon-plus icon-white"></i> Add Photos</span>
                                          <input type="file" name="file"/>
                                      </span>
                                    </div>
                                </form>
                            </div>
                            <div class="btn btn-success">
                                Request Participants
                            </div>
                        </div>    
                    </div>
                    <div class="span3" >
                            <div id="slider-code">
                            	<a class="buttons prev" href="#"><<</a>
                            	<div class="viewport">
                            		<ul class="overview" id="collection-images">
                                        <li></li>
                            		</ul>
                            	</div>
                            	<a class="buttons next" href="#">>></a>
                            </div>
                    </div>
                    
                </div>
          </div>
        </div>
     </div>
</div>
<div class="alert-info pregame team2 team">
    <h2>Team 2</h2>
    <ul id="team2list">
    </ul>
</div>


<div class="alert-error team1 ingame team">
    <h2>Team 1</h2>
    <div id="team1score" class="score">
    </div>
</div>
<div class="controls ingame">
    <div class="timer">
        <h1 id="timeRemaining"></h1>
    </div>
    <div class="container stop-container">
        <div class="btn btn-danger" id="stopbtn">
            Stop Game
        </div>
    </div>
</div>
<div class="alert-info ingame team2 team">
    <h2>Team 2</h2>
    <div id="team2score" class="score">
    </div>
</div>

app/views/wa/index.html.erb
<%= javascript_include_tag "kpa-player" %>

<div class="alert-error team1 ingame team">
    <h2>Team 1</h2>
    <div id="team1score" class="score">
    </div>
</div>
<div class="controls ingame">
    <div class="timer">
        <h1 id="timeRemaining"></h1>
    </div>
</div>
<div class="alert-info ingame team2 team">
    <h2>Team 2</h2>
    <div id="team2score" class="score">
    </div>
</div>